
- id: website_basic
  external_id: website_basic
  service_category_ids:
    - websites
  name: Website Basic
  description: >
    <p>Business designs are productions made for use in internet, application, or visual presentation formats.</p>
  included: Two (2) PNGs. Two (2) source files (web-safe SVGs) can be included for an addtional price. One (1) revision.
  price_range: $50 flat rate
  additional: If you need a different image format (JPG, WEBP, etc.), we will provide that in place of the PNGs or for an additional price.
  image:
    src: /assets/img/lovespresents_embroidery.jpg
    alt: words loves presents embroidered on hat

- id: ecommerce
  external_id: ecommerce

- id: communications
  external_id: communications

- id: tech_maintainance
  external_id: tech_maintainance

- id: consultation
  external_id: consultation

- id: data_management
  external_id: data_management