service_categories:
  - title: "Websites"
    icon: fas fa-tv
    description: >
      <p>Our website offerings provide your small business or creative endeavor with a personalized space on the internet to advertise your services, showcase your productions, and provide a knowledgebase for your clients.</p>
      <p>Take control of your time by off-loading the common tasks of lead-generation and client engagement.</p>
  - title: "Communication"
    icon: fas fa-network-wired    
    description: >
      <p>Our communcation offerings set you up for success with industry standard communication technology to make sure you're always in touch with your team and clients.</p>
      <p>Our packages include email, chat, and personalized social network set-up and training. We also provide account set-up on all of the most popular social media platforms (FaceBook, Twitter, Instagram, etc).</p>
  - title: "e-Commerce"
    icon: fas fa-store
    description: >
      <p>Get your merchandise in front of the <b>global</b> audience with our e-commerce website offerings.</p>
      <p>Our e-commerce packages come with all the advantages of a website, along with store setup and payment gateway to accept online payments.</p>
  - title: "And More"
    icon: fas fa-laptop-medical
    description: >
      <p>In addition to providing bulk packages of website creation, we also provide services for folks who already have a website or business and are needing an update or assistance with data handling, etc.</p>
      <p>Our network of copy-writers, data technicians, and account managers can further off-load some of the more nitty-gritty tasks of online business management, such as website maintenance, data management, and account management.</p>
      <p>If you don't see exactly what you're looking for, <a data-bs-toggle="modal" data-bs-target="#contact-modal" href="#">reach out</a>, and we will get you moving on the next steps toward your solution.</p>

services:
  - id: business_website
    external_id: business_website
    image:
      src: /assets/img/service_categories/oneself_dotdash_logos.jpg
      alt: oneself and dotdash logos
    header:
      title: <div>Business Designs</div>
      background_img:
    description: >
      <p>Business designs are productions made for use in internet, application, or visual presentation formats.</p>
      <p>For small businesses, entrepreneurs, and creators seeking to develop an online presence, we offer <a data-bs-toggle="modal" data-bs-target="#contact-modal" href="#">Logo, Web Interface, and Business Essentials</a> service bundles.</p>
    short_desc: Business designs are for business and web purposes. If you need branding, logo, or business presentation graphics, start here!
    why: Looking for new brand images? Looking to spruce up the ones you have? Just need business cards? Check out these business graphics deals.
    examples:
      - title: One Self
        product: Logo Design, Web UI Design
        description: Graphical interface for the One Self Mighty Network
        url: https://oneself.mn.co
        directory: oneself
        collection_image:
          src: /assets/img/functional_designs/oneself/gold_on_black_separate_os.png
          alt: gold on black os
        items:
          - filename: /assets/img/functional_designs/oneself/circle_s_yellow_red_red.png
            description: Flat color logo
            alt: flat color yellow s in yellow circle red background
    services:
      - name: Basic Logo Package
        description: We will create one logo and one combination mark for your business, app, or online brand.
        included: Two (2) PNGs. Two (2) source files (web-safe SVGs) can be included for an addtional price. One (1) revision.
        price_range: $50 flat rate
        additional: If you need a different image format (JPG, WEBP, etc.), we will provide that in place of the PNGs or for an additional price.
        image:
          src: /assets/img/lovespresents_embroidery.jpg
          alt: words loves presents embroidered on hat
  - id: ecommerce
    external_id: ecommerce
  - id: communications
    external_id: communications
  - id: tech_maintainance
    external_id: tech_maintainance
  - id: consultation
    external_id: consultation
  - id: data_management
    external_id: data_management