
- id: website_basic
  external_id: website_basic
  service_category_ids:
    - websites
  name: Website Basic
  description: >
    <p>We will produce a branded website for you. Perfect for service providers and individuals seeking first time web presence.</p>
  included: One website with three (3) pages and a contact form for collecting leads.
  price_range: $300 - $500
  additional: Additional pages can be added for $50. If you require graphic design or web design services, we can help with that as well!
  image:
    src: /assets/img/computer_cropped.jpg
    alt: computer screen

- id: wordpress_site
  external_id: wordpress_site
  service_category_ids:
    - websites
  name: WordPress Website
  description: >
    <p>We will produce a business or personal WordPress website. WordPress is an industry standard solution for business and personal use. It is ideal for those who plan to produce blog content and/or include dynamic features on their site.</p>
  included: One WordPress site with four (4) pages. One-on-one training on WordPress content creation and routine maintenance.
  price_range: $300 - $700
  additional: WordPress hosting and plugins (if plugins are required) are ongoing services that generally require a regular service fees. Additional pages can be added for $50 each. If you require graphic design or web design services, we can help with that as well!
  image:
    src: /assets/img/wordpress_cropped.jpg
    alt: wordpress logo

- id: shopify_site
  external_id: shopify_site
  service_category_ids:
    - websites
    - ecommerce
  name: Shopify E-commerce
  description: >
    <p>We will produce an e-commerce store on the Shopify e-commerce platform. Perfect for physical products, digital products, print-on-demand graphic designers, and dropshipping entrepreneurs.</p>
  included: One Shopify e-commerce store with three (3) content pages. Initial product catalog setup (up to 5 items) One-on-one training on Shopify store management.
  price_range: $450 - 800
  additional: The Shopify platform requires a monthly service fee (as low as $29/month.) Additional products or pages can be added for an additional price. If you require graphic design or web design services, we can help with that as well!
  image:
    src: /assets/img/loves_presents_embroidery_cropped.jpg
    alt: words loves presents embroidered on hat

- id: woocommerce_site
  external_id: woocommerce_site
  service_category_ids:
    - websites
    - ecommerce
  name: WooCommerce E-commerce
  description: >
    <p>We will produce an e-commerce store on the WooCommerce platform. Perfect for all types of products, print-on-demand, and dropshipping solutions. WooCommerce is built with WordPress, so any personal experience with WordPress will be useful and transferrable.</p>
  included: One WooCommerce e-commerce store with three (3) content pages. Initial product catalog setup (up to 5 items) One-on-one training on WooCommerce store management.
  price_range: $450 - 800
  additional: WordPress hosting and plugins (if plugins are required) are ongoing services that generally require a regular service fees. Additional pages can be added for $50 each. If you require graphic design or web design services, we can help with that as well!
  image:
    src: /assets/img/woocommerce_cropped.jpg
    alt: woo commerce logo

- id: web_application
  external_id: web_application
  service_category_ids:
    - websites
  name: Web Application
  description: >
    <p>We will produce a branded web application with customized functionality specific to your business needs. Perfect for service providers with a service idea that is not satisfied by off-the-shelf solutions.</p>
  included: One web application with custom functionality you need. Three custom features included in the initial contract.
  price_range: Consultation Needed
  additional: Web applications will likely require recurring hosting and 3rd party service fees. Training on any created software included in the price.
  image:
    src: /assets/img/computer_cropped.jpg
    alt: computer screen

- id: mighty_network
  external_id: mighty_network
  service_category_ids:
    - communication
  name: Mighty Network Setup
  description: >
    <p>Mighty Networks is a full-featured custom social network platform. It provides a space to gather fans, community groups, or niche interest communities into one place. Start building your Mighty Network now. Host discussions, event, courses, and monetize your efforts with this platform.</p>
  included: One Mighty Network community setup. Initial site graphics (5 images) and suggested text assets included. One-on-one training and video support.
  price_range: $175
  additional: Additional images and copywriting available. Mighty Network plans range from free to $98/month.
  image:
    src: /assets/img/mighty_networks_cropped.jpg
    alt: mighty networks logo

- id: slack
  external_id: slack
  service_category_ids:
    - communication
  name: Slack Setup
  description: >
    <p>Slack is the industry standard solution for real-time communications between team members and client-bases. It provides chat features, document sharing, and many free software integrations to increase team communication and productivity. </p>
  included: One Slack channel setup. One-on-one Slack management training.
  price_range: $129
  additional: 
  image:
    src: /assets/img/slack_cropped.jpg
    alt: slack logo

- id: zoom
  external_id: zoom
  service_category_ids:
    - communication
  name: Zoom Setup
  description: >
    <p>Zoom is an industry standard video-conferencing tool. A personal Zoom room provides you with the flexibility to speak with individuals around the world in one place. Zoom's additional hosting features make it a great decision for business leaders, course teachers, and those building and maintaining their own budding fanbase.</p>
  included: One Zoom account setup. One-on-one Zoom settings and host training.
  price_range: $129
  additional: 
  image:
    src: /assets/img/zoom_cropped.jpg
    alt: zoom logo

- id: data_entry
  external_id: data_entry
  service_category_ids:
    - additional
  name: Data Entry
  description: >
    <p>Running a business generates data! We will help get your data parsed, organized and entered into a sustainable fashion.</p>
  included: A data set parsed and organized into an spreadsheet or similar organization tool.
  price_range: $50 - 300
  additional: Contact us if you would prefer a custom database solution. Databases are better for a dataset you will be adding to and manipulating often, and may incur additional hosting fees.
  image:
    src: /assets/img/high_ground_cropped.jpg
    alt: high ground tech co logo

- id: copywriting
  external_id: copywriting
  service_category_ids:
    - additional
  name: Copywriting
  description: >
    <p>Our team of copywriters will provide the perfect text, figures, and captions for your next website or offline writing project. No need to spend your time with the gritty details of grammar, punctuation, and tonality, we'll take care of it for you.</p>
  included: A data set parsed and organized into an spreadsheet or similar organization tool.
  price_range: $50 - 300
  additional: Approx. $60 per 500 words or one web page. We also offer writing for paper materials such as posters and pamphlets.
  image:
    src: /assets/img/high_ground_cropped.jpg
    alt: high ground tech co logo

- id: social_media
  external_id: social_media
  service_category_ids:
    - communication
    - additional
  name: Social Media
  description: >
    <p>We provide social media account set up and continued management for your business or brand.</p>
  included: Account set up and regular management on the social media platform of your choice. See our <b><a href="design.highground.tech" target="_blank">Design Studio</a><b> if you require digital graphics and copywriting to post to the account.
  price_range: $80 flat rate
  additional: We offer monthly service plans for social media account management. We will post manage your postings on the social media platform and drive traffic to your page. Contact us for more.
  image:
    src: /assets/img/high_ground_cropped.jpg
    alt: high ground tech co logo

- id: consultation
  external_id: consultation
  service_category_ids:
    - websites
    - communication
    - additional
    - ecommerce
  name: Consultation
  description: >
    <p>We provide consultation for website, web development, web design... Any web questions you may have! If you do or don't have the solution in mind yet, we can help you refine the details into a plan you feel confident in.</p>
  included: One hour consultation with the High Ground Tech Team. Follow-up communication regarding the proposed solution and next steps.
  price_range: $80 flat rate
  additional: We're always happy to help you with your next web technology solution.
  image:
    src: /assets/img/high_ground_cropped.jpg
    alt: high ground tech co logo